name: release
on: 
  push:
    branches:
      - main
    paths:
      - 'stable/**'
  release:
    types: [published, created]

jobs:
  release:
    runs-on: "kube-master"
    steps:

      - name: Configure Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish Helm charts
        uses: fixyourpcmail/helm-gh-pages@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit_email: zdravkocom3@gmail.com
          charts_dir: stable

